name: CD

on:
  push:
    branches:
      - main
      - next

jobs:
  build:
    uses: Seyrinian/seyrinian-tools/.github/workflows/build.yml@main
    with:
      node_version: '20.x'
  release:
    needs: build
    uses: Seyrinian/seyrinian-tools/.github/workflows/release.yml@main
    with:
      node_version: '20.x'
      is_publish: true
    secrets:
      SEMANTIC_BOT_APP_ID: ${{ secrets.SEMANTIC_BOT_APP_ID }}
      SEMANTIC_BOT_PRIVATE_KEY: ${{ secrets.SEMANTIC_BOT_PRIVATE_KEY }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
